### ISSUE TITLE
Additional config needed for successful build

### ISSUE THREAD

**Issue by paulmfinger** [emmaunel/DiscordGo#17]
Heads up, I spent a few hours trying to get this to build this morning, finally got it working after adding some additional lines in /pkg/util/constants/variables.go. Full file contents below:

package constants

var ServerID = "XXXXXXXXXX"
var BotToken = "XXXXXXXXXX"

var DBUsername = "XXXXXXXXXX"
var DBPassword = "XXXXXXXXXX"

I'm not too familiar with Go, so take it with a grain of salt, but maybe you want to include the extra steps in your readme?

**Comment by emmaunel** [comment]
Hey @paulmfinger , thanks for the heads up. I've been making a lot of changes in the backend and forgot to remove unnecessary files and variables. It's gonna be fix soon.

**Comment by emmaunel** [comment]
Hello again @paulmfinger , I've made some changes and updated the README. You should be able to run build the binaries. Let me know how it goes. 

Thanks
